### PR TITLE
Add compatibility for PHP8.1 for full TYPO3 v11 support

### PR DESCRIPTION
**Pull request by jpmschuler**
- various variable initialisation
- minor improvements of composer.json and .gitignore (to allow local development at all)

### CODE REVIEW

**Comment by jpmschuler** [comment]
fixes #25

**Comment by jpmschuler** [comment]
sry found some more, will update later, marking as WIP for time being

**Comment by jpmschuler** [comment]
done (forgot to mark as WIP earlier)

**Comment by svewap** [comment]
Thank you!

**Pull request merged**
